# Generated by Django 3.0.7 on 2021-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyear', '0002_book_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
            ],
        ),
    ]
